name: Build photos

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build it

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "13.2.0"
      - name: npm build photos-ui
        run: |
          cd photos-ui
          npm install
          npm run build
      - name: Use python ${{ matrix.node-version }}
        uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      - name: Python build and test
        run: |
          pip install -U pip
          pip install pipenv
          pipenv sync --dev
          pipenv run pre-commit run -a
          pipenv run pytest
